version: "3.8"
services:
  postgres:
    image: postgres:14.4
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./sql-data/db/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: alexanderlozano950@outlook.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    volumes:
      - ./sql-data/db/pgadmin:/var/lib/pgadmin
