version: '3.9'
services:
  jenkins:
    build: .
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: on-failure
  
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home