version: '3.9'
services:
  mqartemis:
    image: vromero/activemq-artemis:latest
    container_name: mqartemis
    restart: always
    ports:
      - 8161:8161
      - 61616:61616
    environment:
      - ARTEMIS_USERNAME=jlozano
      - ARTEMIS_PASSWORD=jlozano
    volumes:
      - ./artemis:/data/artemis
